import { type WorkflowNodeType } from "@prisma/client";

export interface NodeDefinition {
  type: WorkflowNodeType;
  label: string;
  category: "trigger" | "ai" | "platform" | "utility";
  icon: string;
  color: string;
  description: string;
  inputs: number;
  outputs: number;
  configSchema: Record<string, unknown>;
}

export const NODE_DEFINITIONS: Record<WorkflowNodeType, NodeDefinition> = {
  TRIGGER: {
    type: "TRIGGER",
    label: "Trigger",
    category: "trigger",
    icon: "zap",
    color: "#f59e0b",
    description: "Start workflow execution",
    inputs: 0,
    outputs: 1,
    configSchema: { triggerType: "manual" },
  },
  AI_GENERATE: {
    type: "AI_GENERATE",
    label: "Generate",
    category: "ai",
    icon: "sparkles",
    color: "#8b5cf6",
    description: "Generate AI content",
    inputs: 1,
    outputs: 1,
    configSchema: { format: "linkedin_post" },
  },
  AI_REWRITE: {
    type: "AI_REWRITE",
    label: "Rewrite",
    category: "ai",
    icon: "edit",
    color: "#8b5cf6",
    description: "Rewrite existing content",
    inputs: 1,
    outputs: 1,
    configSchema: { tone: "professional" },
  },
  AI_SUMMARIZE: {
    type: "AI_SUMMARIZE",
    label: "Summarize",
    category: "ai",
    icon: "file-text",
    color: "#8b5cf6",
    description: "Summarize long content",
    inputs: 1,
    outputs: 1,
    configSchema: { length: "short" },
  },
  AI_TRANSLATE: {
    type: "AI_TRANSLATE",
    label: "Translate",
    category: "ai",
    icon: "globe",
    color: "#8b5cf6",
    description: "Translate content to another language",
    inputs: 1,
    outputs: 1,
    configSchema: { targetLanguage: "es" },
  },
  AI_EXPAND: {
    type: "AI_EXPAND",
    label: "Expand",
    category: "ai",
    icon: "maximize",
    color: "#8b5cf6",
    description: "Expand short content into longer form",
    inputs: 1,
    outputs: 1,
    configSchema: { targetLength: "medium" },
  },
  AI_SHORTEN: {
    type: "AI_SHORTEN",
    label: "Shorten",
    category: "ai",
    icon: "minimize",
    color: "#8b5cf6",
    description: "Shorten long content",
    inputs: 1,
    outputs: 1,
    configSchema: { targetLength: "short" },
  },
  AI_OPTIMIZE: {
    type: "AI_OPTIMIZE",
    label: "SEO Optimize",
    category: "ai",
    icon: "search",
    color: "#8b5cf6",
    description: "Optimize content for SEO",
    inputs: 1,
    outputs: 1,
    configSchema: { keywords: [] },
  },
  AI_TONE_CONVERT: {
    type: "AI_TONE_CONVERT",
    label: "Tone Convert",
    category: "ai",
    icon: "message-square",
    color: "#8b5cf6",
    description: "Convert content tone",
    inputs: 1,
    outputs: 1,
    configSchema: { targetTone: "professional" },
  },
  CONDITION: {
    type: "CONDITION",
    label: "Condition",
    category: "utility",
    icon: "git-branch",
    color: "#10b981",
    description: "Branch execution based on conditions",
    inputs: 1,
    outputs: 2,
    configSchema: { field: "", operator: "equals", value: "" },
  },
  DELAY: {
    type: "DELAY",
    label: "Delay",
    category: "utility",
    icon: "clock",
    color: "#10b981",
    description: "Wait before proceeding",
    inputs: 1,
    outputs: 1,
    configSchema: { duration: 60 },
  },
  LOOP: {
    type: "LOOP",
    label: "Loop",
    category: "utility",
    icon: "repeat",
    color: "#10b981",
    description: "Repeat execution",
    inputs: 1,
    outputs: 1,
    configSchema: { count: 3 },
  },
  MERGE: {
    type: "MERGE",
    label: "Merge",
    category: "utility",
    icon: "git-merge",
    color: "#10b981",
    description: "Merge multiple paths",
    inputs: 2,
    outputs: 1,
    configSchema: {},
  },
  SPLIT: {
    type: "SPLIT",
    label: "Split",
    category: "utility",
    icon: "git-branch",
    color: "#10b981",
    description: "Split into parallel paths",
    inputs: 1,
    outputs: 2,
    configSchema: {},
  },
  VARIABLE: {
    type: "VARIABLE",
    label: "Variable",
    category: "utility",
    icon: "code",
    color: "#10b981",
    description: "Set or get a variable",
    inputs: 1,
    outputs: 1,
    configSchema: { operation: "set", name: "", value: "" },
  },
  FORMATTER: {
    type: "FORMATTER",
    label: "Formatter",
    category: "utility",
    icon: "type",
    color: "#10b981",
    description: "Format and transform data",
    inputs: 1,
    outputs: 1,
    configSchema: { format: "markdown" },
  },
  WEBHOOK: {
    type: "WEBHOOK",
    label: "Webhook",
    category: "utility",
    icon: "webhook",
    color: "#10b981",
    description: "Send or receive webhook data",
    inputs: 1,
    outputs: 1,
    configSchema: { method: "POST", url: "" },
  },
  SOCIAL_PUBLISH: {
    type: "SOCIAL_PUBLISH",
    label: "Publish",
    category: "platform",
    icon: "share-2",
    color: "#3b82f6",
    description: "Publish to social platforms",
    inputs: 1,
    outputs: 1,
    configSchema: { platform: "linkedin" },
  },
  EMAIL: {
    type: "EMAIL",
    label: "Email",
    category: "platform",
    icon: "mail",
    color: "#3b82f6",
    description: "Send email notification",
    inputs: 1,
    outputs: 1,
    configSchema: { subject: "", to: "" },
  },
  DATABASE: {
    type: "DATABASE",
    label: "Database",
    category: "utility",
    icon: "database",
    color: "#10b981",
    description: "Read/write database records",
    inputs: 1,
    outputs: 1,
    configSchema: { operation: "read", table: "" },
  },
  HTTP_REQUEST: {
    type: "HTTP_REQUEST",
    label: "HTTP Request",
    category: "utility",
    icon: "globe",
    color: "#10b981",
    description: "Make HTTP requests",
    inputs: 1,
    outputs: 1,
    configSchema: { method: "GET", url: "" },
  },
};

export function getNodeByType(type: WorkflowNodeType): NodeDefinition {
  return NODE_DEFINITIONS[type];
}

export const CATEGORIES = [
  { id: "trigger", label: "Triggers", color: "#f59e0b" },
  { id: "ai", label: "AI Actions", color: "#8b5cf6" },
  { id: "platform", label: "Platforms", color: "#3b82f6" },
  { id: "utility", label: "Utilities", color: "#10b981" },
] as const;
